language: objective-c
osx_image: xcode8
before_install:
    - brew unlink xctool
    - brew update
    - brew install xctool
    - brew link xctool
script:
    # some tests fail stochastically otherwise
    - xctool -project Keystats.xcodeproj -scheme Keystats -sdk macosx run-tests
